<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByDate()
    {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT p.title,p.id,p.created FROM AppBundle:Post p ORDER by p.created DESC'
                    )
                ->getResult();
    }
    
    public function getLatestPost()
    {
    	return $this->getEntityManager()
    			->createQuery(
    					'SELECT p.title,p.post,p.id,p.created FROM AppBundle:Post p ORDER by p.created DESC'
    					)
    			->setMaxResults(4)
    			->getArrayResult();
    }
}
